name: Post thanks comment
on:
  pull_request:
    types: [opened]
    
jobs:
  build:
    name: Post thanks comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Thanks for your PR, have a nice day!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
